
[terminal]
shell.program = "/usr/bin/tmux"
shell.args = ["new-session", "-A", "-s", "main"]


#[env]
#GTK_THEME = "Catppuccin-Mocha"

[window]
dynamic_title = true
opacity = 0.7   # Increased opacity for a slightly more visible window
startup_mode = "Windowed"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 0
y = 0

[font]
normal = { family = "Iosevka Term", style = "Regular" }
bold = { family = "Iosevka Term", style = "Bold" }
italic = { family = "Iosevka Term", style = "Italic" }
bold_italic = { family = "Iosevka Term", style = "Bold Italic" }
size = 14

#[font.normal]
#family = "IosevkaTerm"
#style = "Regular"

#[font.bold]
##amily = "IosevkaTerm"
#style = "Bold"

#[font.italic]
#family = "IosevkaTerm"
#style = "Italic"

[scrolling]
history = 2000
multiplier = 3

[cursor]
blink_interval = 500  # Use milliseconds (500ms = 0.5s)
unfocused_hollow = true


# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
