
schema = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 3
final_space = true
newline = true

[[blocks]]
alignment = "left"
type = "prompt"
#newline =  true


[[blocks.segments]]
foreground = "#FFFFFF" # Deep Sky Blue (OS Icon)
style = "plain"
template = "{{ if .WSL }}WSL at {{ end }}{{.Icon}}"
type = "os"

[blocks.segments.properties]
macos = "mac"

[[blocks.segments]]
foreground = "#BB86FC" # Vibrant Purple (Username)
style = "plain"
template = " {{ .UserName }}: "
type = "session"

[[blocks.segments]]
foreground = "#f5f5f5" # Medium Grey (Path)
style = "plain"
template = "{{ .Path }} "
type = "path"

[blocks.segments.properties]
style = "full"


[[blocks.segments]]
style = "plain"
template = "<#blue>on</> {{ .HEAD }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }} "
type = "git"

[blocks.segments.properties]
branch_icon = ""
fetch_stash_count = true

[[blocks.segments]]
foreground = "#0000ff" # Bright Gold (Python)
style = "powerline"
template = "[\ue235 {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}] "
type = "python"

[[blocks.segments]]
foreground = "#5AC8FA" # Light Blue (Go)
style = "powerline"
template = "[\ue626 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}] "
type = "go"

[[blocks.segments]]
foreground = "#FF8C00" # Dark Orange (Node.js)
style = "powerline"
template = "[\ue718 {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}] "
type = "node"

[[blocks.segments]]
foreground = "#E57373" # Muted Red (Ruby)
style = "powerline"
template = "[\ue791{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}] "
type = "ruby"

[[blocks.segments]]
foreground = "#FF4500" # Rich Orange-Red (Java)
style = "powerline"
template = "[\ue738 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}] "
type = "java"

[[blocks.segments]]
foreground = "#ffffff" # Teal Green (Julia)
style = "powerline"
template = " \ue624 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
type = "julia"



[[blocks.segments]]
foreground = "#7fffd4" # Pure White (Prompt Arrow)
style = "plain"
template = "\u276f "
type = "text"
